##################### DATABASE PROPERTIES ####################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fun-commerce
    username: tama
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082